# Generated by Django 5.1.6 on 2025-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('preco', models.FloatField()),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
